services:
    mhujer_consistence.enum.enum_translator:
        class: Mhujer\ConsistenceBundle\Enum\EnumTranslator
        arguments:
            $translator: '@translator.default'

    Mhujer\ConsistenceBundle\Enum\EnumTranslator: '@mhujer_consistence.enum.enum_translator'
